apiVersion: apps/v1
kind: Deployment

metadata:
  name: pythonstocks-deployment
  labels:
    app: pythonstocks

spec:
  replicas: 5
  selector:
    matchLabels:
      app: pythonstocks
  template:
    metadata:
      labels:
        app: pythonstocks
    spec:
      containers:
        - name: pythonstocks
          image: p1ngo/pythonstocks:4f3334e
          env:
          - name: PYTHONSTOCKS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: db-connection 
                key: db_user
          - name: PYTHONSTOCKS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-connection 
                key: db_password
          - name: PYTHONSTOCKS_DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: db-connection 
                key: db_host
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi